# Generated by Django 3.2.8 on 2021-10-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('SkillId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('StartDate', models.IntegerField()),
                ('EndDate', models.IntegerField()),
            ],
        ),
    ]
