# Generated by Django 3.2.8 on 2021-10-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='Level',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
