# Generated by Django 3.2.8 on 2021-10-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='devops',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
