# Generated by Django 3.2.8 on 2021-10-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_skill_devops'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('DetailId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('StartDate', models.IntegerField()),
                ('EndDate', models.IntegerField()),
                ('Description', models.TextField()),
            ],
        ),
    ]
